### ISSUE TITLE
Header Not Shown on Smaller Displays

### ISSUE THREAD

**Issue by tabuckner** [tabuckner/broskichat#9]
### Prerequisites

* [x] Did you check the FAQs on Discuss?
* [x] Did you perform a cursory search?

### Description

Header not displayed on devices <1024px

### Steps to Reproduce

1. Launch dev server
2. View app
3. Resize Screen <1024px

**Expected behavior:** See responsive header

**Actual behavior:** Header hidden

**Comment by andrewdevelopz** [comment]
This has been fixed.
